version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: privatecal-db-dev
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: calendar_user
      POSTGRES_PASSWORD: calendar_pass
      ENABLE_MIGRATIONS: "true"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
      - ./logs/database:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - privatecal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calendar_user -d calendar_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  database-migrator:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: privatecal-migrator-dev
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: calendar_db
      DB_USER: calendar_user
      DB_PASSWORD: calendar_pass
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      - privatecal-network
    command: /usr/local/bin/run_migrations.sh
    restart: "no"
    profiles:
      - migration

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: privatecal-backend-dev
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - DATABASE_URL=jdbc:postgresql://database:5432/calendar_db
      - DATABASE_USERNAME=calendar_user
      - DATABASE_PASSWORD=calendar_pass
      - JWT_SECRET=privatecal-jwt-secret-key-2024-very-secure-dev
      - NTFY_SERVER_URL=https://ntfy.sh
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_COM_PRIVATECAL=DEBUG
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    networks:
      - privatecal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src:ro
      - ./logs/backend:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api
        - VITE_NTFY_SERVER_URL=https://ntfy.sh
    container_name: privatecal-frontend-dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "24678:24678"  # Vite HMR port
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - privatecal-network
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro

volumes:
  postgres_data_dev:
    driver: local

networks:
  privatecal-network:
    driver: bridge