server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: P-Cal Backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/calendar_db}
    username: ${DATABASE_USERNAME:calendar_user}
    password: ${DATABASE_PASSWORD:calendar_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

  # Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          # socketFactory:
            # port: ${MAIL_PORT:587}
            # class: javax.net.ssl.SSLSocketFactory
            # fallback: false
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    default-encoding: UTF-8
    test-connection: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

logging:
  level:
    com.privatecal: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${LOG_LEVEL:DEBUG}
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Custom application properties
app:
  jwt:
    secret: ${JWT_SECRET:privatecal-jwt-secret-key-2024-very-secure}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}    # default 15 minutes
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # default 7 days

  # Email Configuration
  email:
    enabled: ${EMAIL_ENABLED:true}
    from-address: ${EMAIL_FROM_ADDRESS:noreply@privatecal.com}
    from-name: ${EMAIL_FROM_NAME:P-Cal}
    base-url: ${APP_BASE_URL:http://localhost}
    templates:
      path: classpath:/templates/email/

  ntfy:
    server-url: ${NTFY_SERVER_URL:https://ntfy.sh}
    topic-prefix: ${NTFY_TOPIC_PREFIX:calendar-user-}
    auth-token: ${NTFY_AUTH_TOKEN:}
    enabled: ${NTFY_ENABLED:true}

  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:3000,http://localhost:5173,http://frontend}"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://database:5432/calendar_db}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect